# Generated by Django 4.2.1 on 2023-08-03 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agent_created_at_agent_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='experience_since',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
