# Generated by Django 4.2.1 on 2023-08-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='whatsapp_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
