# Generated by Django 4.2.1 on 2023-10-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_agent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='landline_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
