# Generated by Django 4.2.1 on 2023-10-13 18:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
