# Generated by Django 4.2.1 on 2023-09-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_projects', '0002_alter_projectbed_floor_plan_img_alter_projects_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_media', to='new_projects.projects'),
        ),
    ]
