# Generated by Django 4.2.1 on 2023-09-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_projects', '0002_alter_document_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porjectamenities',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
