# Generated by Django 4.2.1 on 2023-09-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_property_views_count'),
        ('new_projects', '0003_alter_media_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='property_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_property_types', to='property.propertytypes'),
        ),
    ]
