# Generated by Django 4.2.1 on 2023-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_projects', '0003_porjectamenities_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbed',
            name='floor_plan_img',
            field=models.CharField(max_length=200),
        ),
    ]
