# Generated by Django 4.2.1 on 2023-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_projects', '0004_alter_projectbed_floor_plan_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbed',
            name='floor_plan_img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
