# Generated by Django 4.2.1 on 2023-06-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('villa', 'Villa'), ('house', 'House'), ('land', 'Land'), ('apartment', 'Apartment')], default='villa', max_length=20)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('kitchen', models.BooleanField()),
                ('floors', models.IntegerField()),
                ('maid_room', models.BooleanField()),
                ('car_porch', models.BooleanField()),
                ('buy_rent', models.BooleanField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_agent', to='users.agent')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_city', to='property.city')),
            ],
        ),
    ]
