# Generated by Django 4.2.1 on 2023-06-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agent_created_at_agent_updated_at_and_more'),
        ('property', '0005_city_created_at_city_updated_at_country_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('property_type', models.CharField(choices=[('image', 'Image'), ('Video', 'Video')], default='image', max_length=20)),
                ('image_url', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='property',
            name='R_B_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('villa', 'Villa'), ('house', 'House'), ('land', 'Land'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], default='rent', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='address_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_agent', to='users.agent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('villa', 'Villa'), ('house', 'House'), ('land', 'Land'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], default='villa', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_media', to='property.media'),
        ),
    ]
