# Generated by Django 4.2.1 on 2023-06-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_media_property_r_b_type_property_address_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='property_type',
            new_name='media_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='media',
        ),
        migrations.AddField(
            model_name='media',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_media', to='property.property'),
        ),
    ]
