# Generated by Django 4.2.1 on 2023-06-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_rename_property_type_media_media_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='buy_rent',
        ),
    ]
