# Generated by Django 4.2.1 on 2023-06-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_property_buy_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='R_B_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='rent', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_city', to='property.city'),
        ),
    ]
