# Generated by Django 4.2.1 on 2023-07-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0002_agent_created_at_agent_updated_at_and_more'),
        ('property', '0010_remove_property_address_area_remove_property_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='company_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_properties', to='company.companyagent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_properties', to='users.agent'),
        ),
    ]
