# Generated by Django 4.2.1 on 2023-07-12 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_property_company_agent_alter_property_agent'),
        ('property', '0011_propertylocation'),
    ]

    operations = [
    ]
