# Generated by Django 4.2.1 on 2023-07-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_merge_20230712_1551'),
        ('property', '0012_merge_20230712_2127'),
    ]

    operations = [
    ]
