# Generated by Django 4.2.1 on 2023-07-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_property_price_per_marla_property_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price_per_marla',
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='built_in_wardrobes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='covered_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished_unfurnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen_appliances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='lobby_in_building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='security',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='car_porch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='maid_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('villa', 'Villa'), ('house', 'House'), ('land', 'Land'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('townhouse', 'TownHouse'), ('penthouse', 'PentHouse'), ('fullfloor', 'FullFloor'), ('halffloor', 'HalfFloor'), ('wholebuilding', 'WholeBuilding'), ('bulkrentunit', 'BulkRentUnit'), ('bulksaleunit', 'BulkSaleUnit'), ('bungalow', 'Bungalow'), ('hotelandhotelappartment', 'HotelAndHotelAppartment')], default='villa', max_length=50),
        ),
    ]
