# Generated by Django 4.2.1 on 2023-07-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_remove_property_price_per_marla_property_balcony_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAmenties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_nearby_palces', models.CharField(max_length=250)),
                ('bedrooms', models.IntegerField()),
                ('distance_from_airport', models.IntegerField()),
                ('built_in_year', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('kitchen', models.IntegerField(default=0)),
                ('floors', models.IntegerField(default=0)),
                ('maid_room', models.BooleanField(default=False)),
                ('built_in_wardrobes', models.BooleanField(default=False)),
                ('kitchen_appliances', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('lower_portion', models.BooleanField(default=False)),
                ('Farmhouse', models.BooleanField(default=False)),
                ('electricity_backup', models.BooleanField(default=False)),
                ('furnished_unfurnished', models.BooleanField(default=False)),
                ('covered_parking', models.BooleanField(default=False)),
                ('lobby_in_building', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('parking_space', models.BooleanField(default=False)),
                ('drawing_room', models.BooleanField(default=False)),
                ('study_room', models.BooleanField(default=False)),
                ('laundry_room', models.BooleanField(default=False)),
                ('store_room', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('lounge_sitting_area', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('mosque', models.BooleanField(default=False)),
                ('kids_play_area', models.BooleanField(default=False)),
                ('medical_center', models.BooleanField(default=False)),
                ('community_lawn_garden', models.BooleanField(default=False)),
                ('near_by_school', models.BooleanField(default=False)),
                ('near_by_hospital', models.BooleanField(default=False)),
                ('near_by_shopping_mall', models.BooleanField(default=False)),
                ('other_description', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_amount', models.IntegerField(default=0)),
                ('no_of_inst', models.IntegerField(default=1)),
                ('monthly_inst', models.IntegerField(default=0)),
                ('ready_for_possession', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_types', models.CharField(choices=[('residetial_plot', 'Residential Plot'), ('commercial_plot', 'Commercial Plot'), ('agricultural_land', 'Agricultural Land'), ('Industrial_land', 'Industrial_Land'), ('plot_file', 'Plot File'), ('plot_form', 'Plot Form')], default='residetial_plot', max_length=100)),
                ('home_types', models.CharField(choices=[('house', 'House'), ('flat', 'Flat'), ('upper_portion', 'Uper Portion'), ('lower_portion', 'Lower Portion'), ('farm_house', 'Farm House'), ('room', 'Room'), ('pent_house', 'Pent House')], default='house', max_length=100)),
                ('commercial_types', models.CharField(choices=[('office', 'Office'), ('shop', 'Shop'), ('warehouse', 'WareHouse'), ('factory', 'Factory'), ('building', 'Building'), ('other', 'other')], default='office', max_length=100)),
                ('unit_types', models.CharField(choices=[('marla', 'Marla'), ('sqft', 'Sq.Ft.'), ('sqm', 'Sq.M.'), ('sqyd', 'Sq.Yd.'), ('kanal', 'Kanal')], default='marla', max_length=100)),
                ('other_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='date',
        ),
        migrations.RemoveField(
            model_name='country',
            name='date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='built_in_wardrobes',
        ),
        migrations.RemoveField(
            model_name='property',
            name='car_porch',
        ),
        migrations.RemoveField(
            model_name='property',
            name='covered_parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnished_unfurnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='property',
            name='kitchen_appliances',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lobby_in_building',
        ),
        migrations.RemoveField(
            model_name='property',
            name='maid_room',
        ),
        migrations.RemoveField(
            model_name='property',
            name='security',
        ),
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='landline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='amenties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.propertyamenties'),
        ),
        migrations.AddField(
            model_name='property',
            name='installment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.propertyinstallment'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.propertytypes'),
        ),
    ]
