# Generated by Django 4.2.1 on 2023-07-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_propertyamenties_propertyinstallment_propertytypes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='size_sqf',
        ),
        migrations.AddField(
            model_name='propertytypes',
            name='size_sqf',
            field=models.IntegerField(default=0),
        ),
    ]
