# Generated by Django 4.2.1 on 2023-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_rename_mobile_property_secondry_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytypes',
            name='commercial_types',
            field=models.CharField(blank=True, choices=[('null', 'Null'), ('office', 'Office'), ('shop', 'Shop'), ('warehouse', 'WareHouse'), ('factory', 'Factory'), ('building', 'Building'), ('other', 'other')], default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypes',
            name='home_types',
            field=models.CharField(blank=True, choices=[('null', 'Null'), ('house', 'House'), ('flat', 'Flat'), ('upper_portion', 'Uper Portion'), ('lower_portion', 'Lower Portion'), ('farm_house', 'Farm House'), ('room', 'Room'), ('pent_house', 'Pent House')], default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypes',
            name='plot_types',
            field=models.CharField(blank=True, choices=[('null', 'Null'), ('residetial_plot', 'Residential Plot'), ('commercial_plot', 'Commercial Plot'), ('agricultural_land', 'Agricultural Land'), ('Industrial_land', 'Industrial_Land'), ('plot_file', 'Plot File'), ('plot_form', 'Plot Form')], default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertytypes',
            name='unit_types',
            field=models.CharField(blank=True, choices=[('null', 'Null'), ('marla', 'Marla'), ('sqft', 'Sq.Ft.'), ('sqm', 'Sq.M.'), ('sqyd', 'Sq.Yd.'), ('kanal', 'Kanal')], default='marla', max_length=100, null=True),
        ),
    ]
