# Generated by Django 4.2.1 on 2023-08-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_rename_mobile_property_secondry_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyamenties',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertyamenties',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertyamenties',
            name='built_in_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertyamenties',
            name='distance_from_airport',
            field=models.IntegerField(null=True),
        ),
    ]
