# Generated by Django 4.2.1 on 2023-08-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_propertytypes_commercial_types_and_more'),
        ('property', '0020_rename_farmhouse_propertyamenties_farmhouse_and_more'),
    ]

    operations = [
    ]
