# Generated by Django 4.2.1 on 2023-08-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_alter_propertyamenties_built_in_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyamenties',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertyamenties',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
    ]
