# Generated by Django 4.2.1 on 2023-09-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_propertyamenties_built_in_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
