# Generated by Django 4.2.1 on 2023-10-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_property_admin_check_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.AddField(
            model_name='propertylocation',
            name='city_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
