# Generated by Django 4.2.1 on 2023-10-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_alter_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytypes',
            name='home_types',
            field=models.CharField(blank=True, choices=[('null', 'Null'), ('house', 'House'), ('villa', 'Villa'), ('flat', 'Flat'), ('upper_portion', 'Uper Portion'), ('lower_portion', 'Lower Portion'), ('farm_house', 'Farm House'), ('room', 'Room'), ('pent_house', 'Pent House')], default='null', max_length=100, null=True),
        ),
    ]
